name: genesis
favicon: null
layout_spectrum: 0.64716
typography_spectrum: 0.66066
title: Genesis Clinics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.7676492796745151
  saturation: 0.5514624905772507
  rhythmicContrast: 0.9022263528313488
purpose: []
